name: Unit Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        name: PHP ${{ matrix.php }}
        strategy:
            fail-fast: true
            matrix:
                php: [7.3, 7.4, 8.0]
                include:
                    -   laravel: 8.*
                        testbench: 6.*
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v1
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
            -   name: Install dependencies
                run: composer install
            -   name: Composer Autoload
                run: composer dump-autoload --optimize
            -   name: Execute tests
                run: vendor/bin/testbench package:test
            -   name: Catch Testbench Laravel.log on Fail
                if: failure()
                uses: actions/upload-artifact@v2
                with:
                    name: testbench laravel log
                    path: ./vendor/orchestra/testbench-core/laravel/storage/logs/laravel.log
